name: ai_date
description: A new flutter project for a dating app with artificial intelligence integration.

publish_to: 'none' 

version: 1.0.1+6

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  animate_do: ^3.1.2
  intl_phone_number_input: ^0.7.3+1
  flutter_svg: ^2.0.7
  gradient_widgets: ^0.6.0
  pin_code_fields: ^8.0.1
  marquee: ^2.2.3
  dio: ^5.3.3
  toggle_switch: ^2.1.0
  intl: ^0.18.1
  dotted_border: ^2.1.0
  location: ^5.0.3
  appinio_swiper: ^2.0.3
  flutter_native_splash: ^2.3.4
  skeletonizer: ^0.8.0
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^5.0.11
  audioplayers: ^5.2.0
  social_media_recorder: ^1.1.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  record: ^4.4.4
  audio_waveforms: ^1.0.4
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  # voice_message_package: ^1.0.41
  # flutter_secure_storage: ^9.0.0
  # pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/svgs/
    - assets/lotties/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
    # - family: Inter
    #   fonts:
    #     - asset: assets/fonts/Inter-Regular.ttf
    #     - asset: assets/fonts/Inter-Light.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
