// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqFbgiLnrdiLhv1Iz5cfQ8GZL5qwidfM',
    appId: '1:615701910692:android:bffd0637908a1eb0c50231',
    messagingSenderId: '615701910692',
    projectId: 'aidate-test',
    storageBucket: 'aidate-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAflM76V6KzsVQhhSbLbxbUYjU0yeVrCjE',
    appId: '1:615701910692:ios:82621d816e3a231ac50231',
    messagingSenderId: '615701910692',
    projectId: 'aidate-test',
    storageBucket: 'aidate-test.appspot.com',
    androidClientId: '615701910692-dfs38hg3o1jo4q7ocdoeklgi3luak84o.apps.googleusercontent.com',
    iosClientId: '615701910692-8hhlp0r1d71mrg7485sfa48m6etfqs7l.apps.googleusercontent.com',
    iosBundleId: 'com.enterprise.ntsprint.aiDate',
  );
}
